<?php

use Illuminate\Database\Seeder;

class EmployeeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tb_employee')->insert([
            [   
                'id' =>3,
                'employeeId'=>0001,
                'emp_first_name'=>'Demo',
                'emp_lastName'=> 'One',
                'branch_id'=>1,
                'emp_department_id'=>1,
                'emp_designation_id'=>1,
                'emp_gender_id'=>1,
                'emp_shift_id'=>1,
                'emp_father_name'=>'Demo',
                'emp_mother_name'=>'Demo',
                'emp_email'=>'demo_one@email.com',
                'emp_phone'=>'34534534',
                'emp_dob'=>date('Y-m-d'),
                'emp_joining_date'=>date('Y-m-d'),
                'emp_probation_period'=>6,
                'emp_religion'=>'Hindu',
                'emp_marital_status'=>1,
                'emp_blood_group'=>1,
                'emp_bank_account'=>435435,
                'emp_bank_info'=>'Uttara Dhaka',
                'emp_card_number'=>45,
                'emp_nid'=>34543543,
                'emp_nationality'=>'Bangladeshi',
                'emp_ot_status'=>1,
                'emp_parmanent_address'=>'Uttara,Dhaka',
                'emp_current_address'=>'Uttara,Dhaka',
                'emp_emergency_phone'=>32423432,
                'emp_emergency_address'=>'Uttara,Dhaka',
                'emp_account_status'=>1,
            ],
            [   
                'id' =>4,
                'employeeId'=>0002,
                'emp_first_name'=>'Demo',
                'emp_lastName'=> 'Two',
                'branch_id'=>1,
                'emp_department_id'=>1,
                'emp_designation_id'=>1,
                'emp_gender_id'=>2,
                'emp_shift_id'=>2,
                'emp_father_name'=>'Test',
                'emp_mother_name'=>'Demo',
                'emp_email'=>'demo_two@email.com',
                'emp_phone'=>'34534534456',
                'emp_dob'=>date('Y-m-d'),
                'emp_joining_date'=>date('Y-m-d'),
                'emp_probation_period'=>6,
                'emp_religion'=>'Muslim',
                'emp_marital_status'=>1,
                'emp_blood_group'=>1,
                'emp_bank_account'=>435435325,
                'emp_bank_info'=>'Uttara Dhaka',
                'emp_card_number'=>47,
                'emp_nid'=>34543545678834,
                'emp_nationality'=>'Bangladeshi',
                'emp_ot_status'=>1,
                'emp_parmanent_address'=>'Uttara,Dhaka',
                'emp_current_address'=>'Uttara,Dhaka',
                'emp_emergency_phone'=>3242343245345,
                'emp_emergency_address'=>'Uttara,Dhaka',
                'emp_account_status'=>1,
            ],
            [   
                'id' =>5,
                'employeeId'=>0003,
                'emp_first_name'=>'Branch Manager',
                'emp_lastName'=> 'Two',
                'branch_id'=>1,
                'emp_department_id'=>1,
                'emp_designation_id'=>1,
                'emp_gender_id'=>2,
                'emp_shift_id'=>2,
                'emp_father_name'=>'Test',
                'emp_mother_name'=>'Demo',
                'emp_email'=>'branch_manager@email.com',
                'emp_phone'=>'34534534456',
                'emp_dob'=>date('Y-m-d'),
                'emp_joining_date'=>date('Y-m-d'),
                'emp_probation_period'=>6,
                'emp_religion'=>'Muslim',
                'emp_marital_status'=>1,
                'emp_blood_group'=>1,
                'emp_bank_account'=>435435325,
                'emp_bank_info'=>'Uttara Dhaka',
                'emp_card_number'=>47,
                'emp_nid'=>34543545678834,
                'emp_nationality'=>'Bangladeshi',
                'emp_ot_status'=>1,
                'emp_parmanent_address'=>'Uttara,Dhaka',
                'emp_current_address'=>'Uttara,Dhaka',
                'emp_emergency_phone'=>3242343245345,
                'emp_emergency_address'=>'Uttara,Dhaka',
                'emp_account_status'=>1,
            ],
            [   
                'id' =>6,
                'employeeId'=>0004,
                'emp_first_name'=>'Branch Manager2',
                'emp_lastName'=> 'Two',
                'branch_id'=>2,
                'emp_department_id'=>1,
                'emp_designation_id'=>1,
                'emp_gender_id'=>2,
                'emp_shift_id'=>2,
                'emp_father_name'=>'Test',
                'emp_mother_name'=>'Demo',
                'emp_email'=>'branch_manager2@email.com',
                'emp_phone'=>'34534534456',
                'emp_dob'=>date('Y-m-d'),
                'emp_joining_date'=>date('Y-m-d'),
                'emp_probation_period'=>6,
                'emp_religion'=>'Muslim',
                'emp_marital_status'=>1,
                'emp_blood_group'=>1,
                'emp_bank_account'=>435435325,
                'emp_bank_info'=>'Uttara Dhaka',
                'emp_card_number'=>47,
                'emp_nid'=>34543545678834,
                'emp_nationality'=>'Bangladeshi',
                'emp_ot_status'=>1,
                'emp_parmanent_address'=>'Uttara,Dhaka',
                'emp_current_address'=>'Uttara,Dhaka',
                'emp_emergency_phone'=>3242343245345,
                'emp_emergency_address'=>'Uttara,Dhaka',
                'emp_account_status'=>1,
            ],
        ]);
    }
}
